#!/usr/bin/env python3
"""The relay's log says which names changed route, not how many.

Runs the real apply_profiles and apply_custom_domains against a relay laid out
in a temporary directory, with systemctl and nft answered by stand-ins, and
reads what they print. Also holds the template resolvers to the main
resolver's settings, which they lost when the file holding them stopped
being shared.
"""
import contextlib
import importlib.machinery
import importlib.util
import io
import os
import shutil
import sys
import tempfile

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
fails = []


def check(label, cond, detail=""):
    print(("  ok   " if cond else "  FAIL ") + label +
          ((" - " + str(detail)[:700]) if detail and not cond else ""))
    if not cond:
        fails.append(label)


spec = importlib.util.spec_from_loader(
    "sync", importlib.machinery.SourceFileLoader(
        "sync", os.path.join(HERE, "..", "templates", "smartdns-sync")))
sync = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sync)

ME = "198.51.100.1"
tmp = tempfile.mkdtemp()
d_main, d_base, d_prof = (os.path.join(tmp, n) for n in ("dnsmasq.d", "base", "profiles"))
for d in (d_main, d_base, d_prof):
    os.makedirs(d)


def put(path, lines):
    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


SETTINGS = ["no-resolv", "server=1.1.1.1", "server=8.8.8.8", "cache-size=10000",
            "domain-needed", "bogus-priv", "no-hosts", "bind-interfaces",
            "listen-address=127.0.0.1,%s" % ME]
put(os.path.join(d_main, "smart-dns.conf"),
    ["# generated by the smart-dns installer - do not edit by hand"] + SETTINGS +
    ["", "# domains answered with this relay",
     "address=/google.com/%s" % ME, "address=/spotify.com/%s" % ME])
put(os.path.join(d_main, "bypass.conf"), ["server=/gosredirector.ea.com/1.1.1.1"])
pins = os.path.join(d_main, "epic-pins.conf")
put(pins, ["# generated by epic-pin", "address=/pin.epicgames.com/203.0.113.9"])
put(os.path.join(d_main, "no-aaaa.conf"), ["filter-AAAA"])
# Already mirrored, so the test makes no symlinks (Windows may not allow them).
shutil.copy(os.path.join(d_main, "no-aaaa.conf"), os.path.join(d_base, "no-aaaa.conf"))

sync.DNSMASQ_D, sync.BASE_DIR, sync.PROFILE_DIR = d_main, d_base, d_prof
sync.HIJACK_CONF = os.path.join(d_main, "smart-dns.conf")
sync.BYPASS_CONF = os.path.join(d_main, "bypass.conf")
sync.CUSTOM_CONF = os.path.join(d_main, "50-smartdns-custom.conf")
sync.EPIC_PINS = pins
sync.CFG = {"SELF_IP": ME}


class R:
    def __init__(self, out="", rc=0):
        self.stdout, self.returncode, self.stderr = out, rc, ""


running, calls = set(), []
SETS = ["prof_2"]


def fake_sh(*args):
    calls.append(args)
    if args[:2] == ("systemctl", "is-active"):
        return R("active\n" if args[2] in running else "inactive\n")
    if args[:2] == ("systemctl", "restart"):
        running.add(args[2])
    if args[:2] == ("systemctl", "stop"):
        running.discard(args[2])
    if args[:2] == ("systemctl", "list-units"):
        return R("".join("%s.service loaded active running dns\n" % u
                         for u in sorted(running) if u.startswith("smartdns-dns@")))
    # `list sets ip <table>` is not valid nft - it takes a family only - so
    # only the whole-table listing is answered. A command the real nft would
    # refuse gets nothing here either.
    if args[:1] == ("/usr/sbin/nft",) and args[1:3] == ("list", "table"):
        return R("table ip smartdns_nat {\n" +
                 "".join("\tset %s {\n\t\ttype ipv4_addr\n\t}\n" % s for s in SETS) + "}\n")
    return R()


sync.sh = fake_sh
NAMES = {"1": "کامل", "2": "test"}


def apply(profiles, assignment=None, restart=False, names=NAMES):
    calls.clear()
    out = io.StringIO()
    with contextlib.redirect_stdout(out):
        sync.apply_profiles(profiles, assignment or {}, restart=restart, names=names)
    return out.getvalue()


def spec(routed=("spotify.com", "gemini.google.com"), custom=("kmplayer.com",),
         bypass=("gosredirector.ea.com",), pins=True):
    return {"2": {"routed": list(routed), "custom": list(custom),
                  "bypass": list(bypass), "pins": pins}}


conf = os.path.join(d_prof, "2.conf")

print("a template's resolver gets the main resolver's settings")
out = apply(spec(), {"198.51.100.20": "2"})
text = open(conf).read()
for s in SETTINGS:
    check("it has %s" % s, s in text.splitlines(), text)
check("but none of the main resolver's rules",
      "address=/google.com/" not in text, text)
check("and still its own", "address=/spotify.com/%s" % ME in text
      and "address=/kmplayer.com/%s" % ME in text, text)

print("its first start is logged by name, with what it carries")
check("named, on its port",
      "template 2 (test) on port 5300 restarted - routes 3, bypasses 1, pins 1" in out, out)

print("nothing changed, nothing said")
out = apply(spec(), {"198.51.100.20": "2"})
check("no restart", not any(c[:2] == ("systemctl", "restart") for c in calls), calls)
check("and no log line", "restarted" not in out, out)

print("a change is logged as the names that moved")
out = apply(spec(routed=("spotify.com",), custom=("kmplayer.com", "example.org")),
            {"198.51.100.20": "2"})
check("the one that stopped routing", "-gemini.google.com" in out, out)
check("the one that started", "+example.org" in out, out)
check("under 'routes'", "restarted - routes " in out, out)
check("and the resolver was restarted",
      ("systemctl", "restart", "smartdns-dns@2") in calls, calls)

out = apply(spec(routed=("spotify.com",), custom=("kmplayer.com", "example.org"),
                 bypass=("gosredirector.ea.com", "stun.example.net")),
            {"198.51.100.20": "2"})
check("a new bypass is logged as one", "bypasses +stun.example.net" in out, out)

print("a pin moving to a new address is a change worth a line")
put(pins, ["# generated by epic-pin", "address=/pin.epicgames.com/203.0.113.10"])
out = apply(spec(routed=("spotify.com",), custom=("kmplayer.com", "example.org"),
                 bypass=("gosredirector.ea.com", "stun.example.net")),
            {"198.51.100.20": "2"})
check("both addresses named",
      "+pin.epicgames.com=203.0.113.10" in out and "-pin.epicgames.com=203.0.113.9" in out,
      out)

print("a big change is summarised, not dumped")
many = ["n%02d.example" % i for i in range(40)]
out = apply(spec(routed=["spotify.com"] + many), {"198.51.100.20": "2"})
check("the first fifteen, then a count", "(+25 more)" in out, out)
check("on one line", len([l for l in out.splitlines() if "restarted" in l]) == 1, out)

print("a restart with no change says why it happened")
last = spec(routed=["spotify.com"] + many)
running.discard("smartdns-dns@2")
out = apply(last, {"198.51.100.20": "2"})
check("it was not running", "restarted - was not running" in out, out)
out = apply(last, {"198.51.100.20": "2"}, restart=True)
check("the shared config changed", "restarted - shared config changed" in out, out)

print("customers moving between templates")
out = apply(last, {"198.51.100.20": "2", "198.51.100.21": "2"})
check("one joining is logged", "198.51.100.21 now on template 2 (test)" in out, out)
check("the one already there is not", "198.51.100.20 now on" not in out, out)
out = apply(last, {"198.51.100.21": "2"})
check("one leaving is logged", "198.51.100.20 left template 2 (test)" in out, out)

print("a leftover set with no rule is cleared away")
SETS[:] = ["prof_2", "prof_9"]
apply(last, {"198.51.100.21": "2"})
check("the leftover is deleted",
      ("/usr/sbin/nft", "delete", "set", "ip", sync.NAT_TABLE, "prof_9") in calls, calls)
check("the one in use is not",
      ("/usr/sbin/nft", "delete", "set", "ip", sync.NAT_TABLE, "prof_2") not in calls, calls)
SETS[:] = ["prof_2"]

print("a template nobody is on any more")
# Deleted in the panel, so its name is no longer in what the panel sends.
out = apply({}, {}, names={"1": "کامل"})
check("is retired by name, even once the panel has forgotten it",
      "template 2 (test) retired - nobody is on it" in out, out)
check("its resolver stopped", ("systemctl", "stop", "smartdns-dns@2") in calls, calls)

print("custom domains are logged by name too")
out = io.StringIO()
with contextlib.redirect_stdout(out):
    sync.apply_custom_domains(["kmplayer.com"])
    sync.apply_custom_domains(["kmplayer.com", "example.org"])
    sync.apply_custom_domains(["example.org"])
lines = out.getvalue().splitlines()
check("the first one", lines[:1] == ["custom domains: +kmplayer.com (now 1)"], lines)
check("one added", "custom domains: +example.org (now 2)" in lines, lines)
check("one removed", "custom domains: -kmplayer.com (now 1)" in lines, lines)

shutil.rmtree(tmp, ignore_errors=True)
print()
if fails:
    print("%d FAILED: %s" % (len(fails), ", ".join(fails)))
    sys.exit(1)
print("all checks passed")
