#!/usr/bin/env python3
"""smartdns-rules: what each template's resolver does with a name.

The rules are read the way dnsmasq applies them - longest domain wins, and at
a tie address= beats server= - and checked against what a resolver actually
answers. Both halves run here against a relay laid out in a temporary
directory, with small DNS servers standing in for the dnsmasq instances.
"""
import contextlib
import importlib.machinery
import importlib.util
import io
import json
import os
import shutil
import socket
import struct
import sys
import tempfile
import threading

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
fails = []


def check(label, cond, detail=""):
    print(("  ok   " if cond else "  FAIL ") + label +
          ((" - " + str(detail)[:600]) if detail and not cond else ""))
    if not cond:
        fails.append(label)


def load(name, path):
    spec = importlib.util.spec_from_loader(
        name, importlib.machinery.SourceFileLoader(name, path))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


rules = load("rules", os.path.join(HERE, "..", "templates", "smartdns-rules"))
ME = "198.51.100.1"


# ------------------------------------------------------- stand-in resolvers
class FakeDNS:
    """Answers A queries from a table; silent=True answers nothing at all."""

    def __init__(self, table, silent=False):
        self.table, self.silent = table, silent
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sock.bind(("127.0.0.1", 0))
        self.port = self.sock.getsockname()[1]
        threading.Thread(target=self.serve, daemon=True).start()

    def serve(self):
        while True:
            try:
                data, peer = self.sock.recvfrom(4096)
            except OSError:
                return
            if self.silent:
                continue
            off, labels = 12, []
            while data[off]:
                labels.append(data[off + 1:off + 1 + data[off]].decode())
                off += 1 + data[off]
            question = data[12:off + 5]
            ips = self.table.get(".".join(labels), [])
            reply = data[:2] + struct.pack(">HHHHH", 0x8180, 1, len(ips), 0, 0)
            reply += question
            for ip in ips:
                reply += struct.pack(">HHHIH", 0xC00C, 1, 1, 60, 4) + socket.inet_aton(ip)
            self.sock.sendto(reply, peer)


main_dns = FakeDNS({"gemini.google.com": [ME], "spotify.com": [ME],
                    "gosredirector.ea.com": ["159.153.0.9"],
                    "pin.epicgames.com": ["203.0.113.9"],
                    "kmplayer.com": [ME], "example.org": ["93.184.216.34"]})
# The template: routes Spotify, not Google.
prof_dns = FakeDNS({"gemini.google.com": ["142.250.1.1"], "spotify.com": [ME],
                    "kmplayer.com": ["104.21.0.1"]})

# ------------------------------------------------------ a relay on disk
tmp = tempfile.mkdtemp()
d_main = os.path.join(tmp, "dnsmasq.d")
d_base = os.path.join(tmp, "base")
d_prof = os.path.join(tmp, "profiles")
for d in (d_main, d_base, d_prof):
    os.makedirs(d)


def put(path, lines):
    with open(path, "w", newline="\n", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


put(os.path.join(d_main, "smart-dns.conf"), [
    "# generated by the smart-dns installer", "no-resolv", "server=1.1.1.1",
    "server=8.8.8.8", "cache-size=10000", "listen-address=127.0.0.1,%s" % ME,
    "address=/google.com/%s" % ME, "address=/spotify.com/%s" % ME,
    "address=/ea.com/%s" % ME, "address=/epicgames.com/%s" % ME,
    "address=/tie.example/%s" % ME, "address=/one.test/two.test/%s" % ME])
put(os.path.join(d_main, "bypass.conf"), [
    "server=/gosredirector.ea.com/1.1.1.1", "server=/gosredirector.ea.com/8.8.8.8",
    "server=/tie.example/1.1.1.1"])
put(os.path.join(d_main, "epic-pins.conf"), ["address=/pin.epicgames.com/203.0.113.9"])
put(os.path.join(d_main, "50-smartdns-custom.conf"), ["address=/kmplayer.com/%s" % ME])
put(os.path.join(d_main, "no-aaaa.conf"), ["filter-AAAA"])
put(os.path.join(d_main, "README"), ["Files in this directory are read by dnsmasq."])
put(os.path.join(d_main, "smart-dns.conf.dpkg-old"), ["address=/stale.example/%s" % ME])
shutil.copy(os.path.join(d_main, "no-aaaa.conf"), os.path.join(d_base, "no-aaaa.conf"))
put(os.path.join(d_prof, "2.conf"), [
    "# generated by smartdns-sync - do not edit", "port=%d" % prof_dns.port,
    "address=/spotify.com/%s" % ME, "server=/gosredirector.ea.com/1.1.1.1"])

env = os.path.join(tmp, "sync.env")
put(env, ["PANEL_HOST=203.0.113.50", "SELF_IP=%s" % ME])
names = os.path.join(tmp, "templates.json")
put(names, [json.dumps({"default": 1, "names": {"1": "کامل", "2": "test",
                                                "3": "empty"}}, ensure_ascii=False)])

rules.SYNC_ENV, rules.DNSMASQ_D, rules.BASE_DIR = env, d_main, d_base
rules.PROFILE_DIR, rules.TEMPLATE_NAMES = d_prof, names
rules.MAIN_PORT = main_dns.port
rules.TIMEOUT = 1.0

# The firewall and systemd, as the relay would answer. prof_9 is a leftover
# set with no rule pointing at it - the kind found on the live relay.
NFT_CHAIN = ("table ip smartdns_nat {\n chain pre {\n"
             "  ip saddr @prof_2 udp dport 53 redirect to :%d\n"
             "  ip saddr @prof_2 tcp dport 53 redirect to :%d\n }\n}\n"
             % (prof_dns.port, prof_dns.port))
SETS = {"prof_2": ["198.51.100.20"], "prof_9": ["198.51.100.30"]}
ACL_ROWS = [{"ip": ip, "name": "u%d" % i, "up": 0, "down": 0, "total": 0}
            for i, ip in enumerate(["198.51.100.10", "198.51.100.20",
                                    "198.51.100.30"], 1)]


class R:
    def __init__(self, out, rc=0):
        self.stdout, self.returncode, self.stderr = out, rc, ""


def fake_run(*args):
    if args[:2] == (rules.NFT, "list"):
        return R(NFT_CHAIN)
    if args[:3] == (rules.NFT, "-j", "list"):
        return R(json.dumps({"nftables": [{"metainfo": {}}, {"set": {
            "name": args[-1], "elem": SETS.get(args[-1], [])}}]}))
    if args[0] == rules.ACL:
        return R(json.dumps(ACL_ROWS))
    if args[0] == "systemctl":
        return R("active\n")
    return None


rules.run = fake_run


def call(*argv):
    out = io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(out):
        rc = rules.main(list(argv))
    return rc, out.getvalue()


# ------------------------------------------------------------------ rules
print("reading the rules the way dnsmasq applies them")
rs = rules.resolvers()
main, prof = rs[0], rs[1]
check("two resolvers: the default and template 2", [r.key for r in rs] == ["main", "2"],
      [r.key for r in rs])
check("the default is named from the panel", main.label() == "کامل (default)", main.label())
check("and so is the template", prof.label() == "test", prof.label())


def kind(res, name):
    return rules.meaning(res.decide(name), ME)[0]


check("a routed parent covers its subdomain", kind(main, "gemini.google.com") == "relay")
check("a longer bypass beats the routed parent",
      kind(main, "gosredirector.ea.com") == "direct")
check("at a tie address= beats server=", kind(main, "tie.example") == "relay")
check("a pinned host beats the routed parent",
      kind(main, "pin.epicgames.com") == "pinned")
check("a custom domain is found in its own file",
      main.decide("kmplayer.com").source == "50-smartdns-custom.conf")
check("both names of a two-domain line count",
      kind(main, "one.test") == "relay" and kind(main, "two.test") == "relay")
check("upstream server= lines are not rules about any name",
      not any(r.domain in ("1.1.1.1", "8.8.8.8") for r in main.rules))
check("a .dpkg-old file is not read, as dnsmasq does not",
      kind(main, "stale.example") == "direct")
check("the template has no rule for what it does not route",
      prof.decide("gemini.google.com") is None)
check("and routes what it does", kind(prof, "spotify.com") == "relay")
check("it does not read the default's files",
      prof.decide("kmplayer.com") is None)
check("a name matched only by suffix text is not a match",
      main.decide("notgoogle.com") is None)

# ------------------------------------------------------------------ check
print("check: the rule, and what the resolver really answers")
rc, out = call("check", "https://Gemini.Google.com/app")
check("a URL is cut down to its name", out.startswith("gemini.google.com"), out)
check("the default redirects it", "relay   address=/google.com/" in out, out)
check("and says which file decided it", "(smart-dns.conf)" in out, out)
check("the template leaves it alone", "direct  no rule" in out, out)
check("each line names its template", "کامل (default)" in out and "test" in out, out)
check("everything agrees, so it exits 0", rc == 0, out)

rc, out = call("check", "gosredirector.ea.com", "pin.epicgames.com", "example.org")
check("a bypass is shown as direct with its rule",
      "direct  server=/gosredirector.ea.com/1.1.1.1" in out, out)
check("a pin as pinned", "pinned  address=/pin.epicgames.com/203.0.113.9" in out, out)
check("a name with no rule anywhere as direct", rc == 0, out)

print("check notices a resolver answering against its own rules")
prof_dns.table["gemini.google.com"] = [ME]       # still on old config
rc, out = call("check", "gemini.google.com")
check("it flags the disagreement", "not what it answered" in out, out)
check("and says what to restart", "systemctl restart smartdns-dns@2" in out, out)
check("and exits 1", rc == 1, rc)
prof_dns.table["gemini.google.com"] = ["142.250.1.1"]

print("and a resolver that does not answer")
dead = FakeDNS({}, silent=True)
saved = rules.MAIN_PORT
rules.MAIN_PORT = dead.port
rc, out = call("check", "spotify.com")
check("it says so", "did not answer - is dnsmasq running?" in out, out)
check("and exits 1", rc == 1, rc)
rules.MAIN_PORT = saved

rc, out = call("check", "not a domain!")
check("junk is refused, not asked", "not a domain" in out and rc == 1, out)

# ----------------------------------------------------------------- summary
print("the summary")
rc, out = call()
lines = {l.split()[-1]: l for l in out.splitlines() if l.strip().endswith(("(default)", "test"))}
check("one line per resolver", len(lines) == 2, out)
row = lines.get("(default)", "").split()
check("the default counts every registered customer not on a template - "
      "including the one in a set no rule uses",
      row[1:2] == ["2"], out)
row = lines.get("test", "").split()
check("the template counts its own", row[1:2] == ["1"], out)
# Seven routed in the main list and the custom one; two bypassed names (one
# written twice, once per public resolver, counts once); one pin.
check("redirect, bypass and pin counts for the default, in names not lines",
      lines.get("(default)", "").split()[2:5] == ["8", "2", "1"], out)
check("a template with no customers is explained, not listed",
      "no resolver here" in out and "empty" not in out, out)

# -------------------------------------------------------------------- show
print("show")
rc, out = call("show", "test")
check("by name", out.startswith("test - resolver on :%d" % prof_dns.port), out)
check("lists what it redirects", "redirected to this relay (1):\n  spotify.com" in out, out)
check("and what it bypasses", "gosredirector.ea.com" in out and "1.1.1.1" in out, out)
rc, out = call("show")
check("with nothing named, the default", out.startswith("کامل (default)"), out)
check("custom domains are marked", "kmplayer.com  [custom]" in out, out)
rc, out = call("show", "empty")
check("a template with no customers says why it has no resolver",
      "no customers" in out and rc == 0, out)
rc, out = call("show", "nope")
check("an unknown one is an error", rc == 1 and "no template" in out, out)

print("the command line")
rc, out = call("-h")
check("-h prints the usage", rc == 0 and "smartdns-rules check DOMAIN" in out, out)
rc, out = call("frobnicate")
check("an unknown command is refused", rc == 2, rc)
rc, out = call("check")
check("check with nothing to check is refused", rc == 2, rc)

# ------------------------------------------------- where the names come from
print("the relay keeps the names the panel sends")
sync = load("sync", os.path.join(HERE, "..", "templates", "smartdns-sync"))
sync.TEMPLATE_NAMES = os.path.join(tmp, "state", "templates.json")
info = {"default": 1, "names": {"1": "کامل", "2": "test"}}
check("written the first time", sync.save_template_names(info) is True)
check("left alone when nothing changed", sync.save_template_names(info) is False)
check("an older panel sending none changes nothing",
      sync.save_template_names(None) is False)
got = json.load(open(sync.TEMPLATE_NAMES, encoding="utf-8"))
check("in the shape smartdns-rules reads", got == info, got)

panel = load("panel", os.path.join(HERE, "..", "templates", "smartdns-panel"))
store = panel.Store(os.path.join(tmp, "panel.db"))
default = store.ensure_default_template([])["id"]
store.run("INSERT INTO templates (name, is_default, created_at) VALUES ('test', 0, ?)",
          (panel.now(),))
tn = store.template_names()
check("the panel sends the default's id", tn["default"] == default, tn)
check("and every name", sorted(tn["names"].values()) == sorted(["کامل", "test"]), tn)
src = open(os.path.join(HERE, "..", "templates", "smartdns-panel"), encoding="utf-8").read()
check("in its /sync answer", '"templates": self.store.template_names()' in src)

print("the installer puts it on the relay")
logic = open(os.path.join(HERE, "installer-logic.sh"), encoding="utf-8").read()
at = logic.find("payload SMARTDNS_RULES > /usr/local/bin/smartdns-rules")
check("it is written", at > 0)
check("inside the relay-only part",
      logic.index('if [ "$ROLE" = relay ]; then\n\n    step "dnsmasq') < at
      < logic.index('step "epic-pin'))
check("and uninstall knows it is ours", "note_file /usr/local/bin/smartdns-rules" in logic)
build = open(os.path.join(HERE, "build-installer.py"), encoding="utf-8").read()
check("the build carries it", '("SMARTDNS_RULES", "templates/smartdns-rules")' in build)

shutil.rmtree(tmp, ignore_errors=True)
print()
if fails:
    print("%d FAILED: %s" % (len(fails), ", ".join(fails)))
    sys.exit(1)
print("all checks passed")
